# sensors:
#  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#    image_topic: /grasp_publish
#    queue_size: 5
#    near_clipping_plane_distance: 0.3
#    far_clipping_plane_distance: 5.0
#    skip_vertical_pixels: 1
#    skip_horizontal_pixels: 1
#    shadow_threshold: 0.2
#    padding_scale: 4.0
#    padding_offset: 0.03
#    filtered_cloud_topic: output_cloud

sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /phoxi_camera_/pointcloud
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud
